version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount database volume for persistence
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/sqlite.db
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
    driver: local
